### ISSUE TITLE
Fotter is not at bottom

### ISSUE THREAD

**Issue by samagragupta** [casbin/casbin-dashboard#69]
Footer is not fixed at the bottom.
![2](https://user-images.githubusercontent.com/32234926/77986233-3604cf80-7334-11ea-8f3b-13f1910a9a6c.gif)

**Comment by devabhixda** [comment]
Already been fixed by @hsluoyz https://github.com/casbin/casbin-dashboard/commit/c823377bd2c260f0cfab361ef1d0bdf405d13036

**Comment by japorized** [comment]
Perhaps it's still missing `position: relative; min-height: 100vh;` for the `div` on [line 44 of `App.js`](https://github.com/casbin/casbin-dashboard/blob/28e4130d93bebeaaf1accc1248d543161c93ba29/web/src/App.js#L44)?

Right now the footer still behaves just as shown in the GIF above.

**Comment by hsluoyz** [comment]
@438561537 please fix it.
